// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/shorturl/v1/shorturl.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on ConvertRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ConvertRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ConvertRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ConvertRequestMultiError,
// or nil if none found.
func (m *ConvertRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ConvertRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetLongURL()) < 1 {
		err := ConvertRequestValidationError{
			field:  "LongURL",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return ConvertRequestMultiError(errors)
	}

	return nil
}

// ConvertRequestMultiError is an error wrapping multiple validation errors
// returned by ConvertRequest.ValidateAll() if the designated constraints
// aren't met.
type ConvertRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ConvertRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ConvertRequestMultiError) AllErrors() []error { return m }

// ConvertRequestValidationError is the validation error returned by
// ConvertRequest.Validate if the designated constraints aren't met.
type ConvertRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ConvertRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ConvertRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ConvertRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ConvertRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ConvertRequestValidationError) ErrorName() string { return "ConvertRequestValidationError" }

// Error satisfies the builtin error interface
func (e ConvertRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sConvertRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ConvertRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ConvertRequestValidationError{}

// Validate checks the field values on ConvertResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ConvertResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ConvertResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ConvertResponseMultiError, or nil if none found.
func (m *ConvertResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ConvertResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ShortURL

	if len(errors) > 0 {
		return ConvertResponseMultiError(errors)
	}

	return nil
}

// ConvertResponseMultiError is an error wrapping multiple validation errors
// returned by ConvertResponse.ValidateAll() if the designated constraints
// aren't met.
type ConvertResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ConvertResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ConvertResponseMultiError) AllErrors() []error { return m }

// ConvertResponseValidationError is the validation error returned by
// ConvertResponse.Validate if the designated constraints aren't met.
type ConvertResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ConvertResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ConvertResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ConvertResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ConvertResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ConvertResponseValidationError) ErrorName() string { return "ConvertResponseValidationError" }

// Error satisfies the builtin error interface
func (e ConvertResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sConvertResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ConvertResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ConvertResponseValidationError{}

// Validate checks the field values on RedirectRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *RedirectRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RedirectRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// RedirectRequestMultiError, or nil if none found.
func (m *RedirectRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *RedirectRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetShortURL()) < 1 {
		err := RedirectRequestValidationError{
			field:  "ShortURL",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return RedirectRequestMultiError(errors)
	}

	return nil
}

// RedirectRequestMultiError is an error wrapping multiple validation errors
// returned by RedirectRequest.ValidateAll() if the designated constraints
// aren't met.
type RedirectRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RedirectRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RedirectRequestMultiError) AllErrors() []error { return m }

// RedirectRequestValidationError is the validation error returned by
// RedirectRequest.Validate if the designated constraints aren't met.
type RedirectRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RedirectRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RedirectRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RedirectRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RedirectRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RedirectRequestValidationError) ErrorName() string { return "RedirectRequestValidationError" }

// Error satisfies the builtin error interface
func (e RedirectRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRedirectRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RedirectRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RedirectRequestValidationError{}

// Validate checks the field values on RedirectResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *RedirectResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RedirectResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// RedirectResponseMultiError, or nil if none found.
func (m *RedirectResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *RedirectResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for LongURL

	if len(errors) > 0 {
		return RedirectResponseMultiError(errors)
	}

	return nil
}

// RedirectResponseMultiError is an error wrapping multiple validation errors
// returned by RedirectResponse.ValidateAll() if the designated constraints
// aren't met.
type RedirectResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RedirectResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RedirectResponseMultiError) AllErrors() []error { return m }

// RedirectResponseValidationError is the validation error returned by
// RedirectResponse.Validate if the designated constraints aren't met.
type RedirectResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RedirectResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RedirectResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RedirectResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RedirectResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RedirectResponseValidationError) ErrorName() string { return "RedirectResponseValidationError" }

// Error satisfies the builtin error interface
func (e RedirectResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRedirectResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RedirectResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RedirectResponseValidationError{}
