// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"shortURL/internal/biz"
	"shortURL/internal/conf"
	"shortURL/internal/data"
	"shortURL/internal/data/sequence"
	"shortURL/internal/server"
	"shortURL/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, confBiz *conf.Biz, logger log.Logger) (*kratos.App, func(), error) {
	db := data.NewDB(confData)
	client := data.NewRedisCli(confData)
	dataData, cleanup, err := data.NewData(confData, db, client, logger)
	if err != nil {
		return nil, nil, err
	}
	shortURLRepo := data.NewShortURLRepo(dataData, logger)
	sequenceUseCase := sequence.NewSeqUseCase(client)
	shortURLUsecase := biz.NewShortURLUsecase(confBiz, shortURLRepo, sequenceUseCase)
	shortURLService := service.NewShortURLService(shortURLUsecase)
	grpcServer := server.NewGRPCServer(confServer, shortURLService, logger)
	httpServer := server.NewHTTPServer(confServer, shortURLService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
