server:
  http:
    addr: 0.0.0.0:8090
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 30s
data:
  database:
    driver: mysql
    source: root:123@tcp(127.0.0.1:13306)/short_url?parseTime=True&loc=Local
  redis:
    addr: 
    # 填哨兵的地址
      - 127.0.0.1:26379
      - 127.0.0.1:26380
      - 127.0.0.1:26381
    read_timeout: 30s
    write_timeout: 30s
biz:
  domain: 127.0.0.1:8090