server:
  http:
    addr: 0.0.0.0:8090
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  database:
    driver: mysql
    source: root:123@tcp(127.0.0.1:13306)/short_url?parseTime=True&loc=Local
  redis:
    addr: 127.0.0.1:16379
    read_timeout: 3s
    write_timeout: 3s
biz:
  domain: 127.0.0.1:8090