// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameShortURLMap = "short_url_map"

// ShortURLMap mapped from table <short_url_map>
type ShortURLMap struct {
	ID       int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CreateAt time.Time `gorm:"column:create_at;not null;default:CURRENT_TIMESTAMP" json:"create_at"`
	UpdateAt time.Time `gorm:"column:update_at;not null;default:CURRENT_TIMESTAMP" json:"update_at"`
	IDDel    int32     `gorm:"column:id_del;not null" json:"id_del"`
	Lurl     string    `gorm:"column:lurl" json:"lurl"`
	LurlMd5  string    `gorm:"column:lurl_md5" json:"lurl_md5"`
	Surl     string    `gorm:"column:surl" json:"surl"`
}

// TableName ShortURLMap's table name
func (*ShortURLMap) TableName() string {
	return TableNameShortURLMap
}
